// Package policy decides whether a path may be edited.
package policy

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/sureshpsc/evolvectl/internal/fsio"
)

// Decision is an allow/deny result.
type Decision struct {
	Allowed bool
	Reason  string
}

// Options configures default protections.
type Options struct {
	AllowGenerated bool
	AllowVendor    bool
}

// AllowPath reports whether rel may be modified.
func AllowPath(root, rel string, body []byte, opt Options) Decision {
	if _, ok := fsio.WithinRoot(root, rel); !ok {
		return Decision{Reason: "path escapes workspace root"}
	}
	slash := filepath.ToSlash(rel)
	if slash == ".git" || strings.HasPrefix(slash, ".git/") || strings.Contains(slash, "/.git/") {
		return Decision{Reason: "refusing to modify .git"}
	}
	base := filepath.Base(rel)
	if isVendor(slash) && !opt.AllowVendor {
		return Decision{Reason: "vendor paths are protected"}
	}
	if !opt.AllowGenerated && (GeneratedPath(slash) || GeneratedContent(body)) {
		return Decision{Reason: "generated files are protected"}
	}
	if binaryExt(base) {
		return Decision{Reason: "binary files are protected"}
	}
	return Decision{Allowed: true, Reason: "allowed"}
}

func isVendor(slash string) bool {
	return slash == "vendor" || strings.HasPrefix(slash, "vendor/") || strings.Contains(slash, "/vendor/")
}

// GeneratedPath matches common generated locations.
func GeneratedPath(slash string) bool {
	parts := strings.Split(slash, "/")
	for _, p := range parts {
		switch p {
		case "generated", "node_modules", ".venv", "venv", "__pycache__", "dist":
			return true
		}
	}
	base := parts[len(parts)-1]
	if strings.HasSuffix(base, ".pb.go") || strings.HasSuffix(base, "_generated.py") {
		return true
	}
	return false
}

// GeneratedContent detects generator banners.
func GeneratedContent(body []byte) bool {
	s := string(body)
	if len(s) > 4000 {
		s = s[:4000]
	}
	low := strings.ToLower(s)
	if strings.Contains(s, "Code generated") && strings.Contains(s, "DO NOT EDIT") {
		return true
	}
	if strings.Contains(low, "generated by") && strings.Contains(low, "do not edit") {
		return true
	}
	return false
}

func binaryExt(base string) bool {
	ext := strings.ToLower(filepath.Ext(base))
	switch ext {
	case ".png", ".jpg", ".jpeg", ".gif", ".webp", ".zip", ".gz", ".tar", ".exe", ".dll", ".so", ".dylib", ".pyc", ".wasm", ".bin", ".pdf":
		return true
	default:
		return false
	}
}

// ReadMaybe reads a file if it exists.
func ReadMaybe(path string) []byte {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	return b
}
