package policy

import "testing"

func TestGeneratedProtected(t *testing.T) {
	body := []byte("// Code generated by mock. DO NOT EDIT.\npackage p\n")
	d := AllowPath(".", "gen.go", body, Options{})
	if d.Allowed {
		t.Fatal(d)
	}
	d = AllowPath(".", "../outside.go", nil, Options{})
	if d.Allowed {
		t.Fatal("escaped root")
	}
}
